services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: market_siparis
      TZ: Europe/Istanbul
    ports:
      - "3309:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: db
      DB_NAME: market_siparis
      TZ: Europe/Istanbul
    ports:
      - "5002:5000" # Dairysense ile çakışmasın diye 5002'ye aldık
    volumes:
      - .:/app

volumes:
  db_data: